from types import SimpleNamespace

NEG = "NEG"
AND = "AND"
OR = "OR"
IMP = "IMP"
IFF = "IFF"
FORALL = "FORALL"
EXISTS = "EXISTS"
IN = "IN"
EQ = "EQ"
CONJUNCTION = "CONJUNCTION"
INTERSECT = "INTERSECT"
UNION = "UNION"
INCLUDES = "INCLUDES"
SEQ = "SEQ"
SET = "SET"
SELECT = "SELECT"

const = SimpleNamespace()
const.NEG = NEG
const.AND = AND
const.OR = OR
const.IMP = IMP
const.IFF = IFF
const.FORALL = FORALL
const.EXISTS = EXISTS
const.IN = IN
const.EQ = EQ
const.CONJUNCTION = CONJUNCTION
const.INTERSECT = INTERSECT
const.UNION = UNION
const.INCLUDES = INCLUDES
const.SEQ = SEQ
const.SET = SET
const.SELECT = SELECT

# PROGRAM

FORMULA = "FORMULA"
ASSUMPTION = "ASSUMPTION"
CONST_DECLARATION = "CONST_DECLARATION"

const.FORMULA = FORMULA
const.ASSUMPTION = ASSUMPTION
const.CONST_DECLARATION = CONST_DECLARATION
