[project]
name = "reason"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.19.0",
    "lark",
]

[tool.uv.sources]
lark = { path = "repositories/lark" }
