name: Reason check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - run: sudo apt install -y build-essential cmake clang zlib1g-dev libgmp-dev python3 curl

      - name: Cache node modules
        id: cache-vampire
        uses: actions/cache@v4
        with:
          path: repositories/vampire/build
          key: ${{ runner.os }}-${{ hashFiles('repositories/vampire/**') }}

      - if: ${{ steps.cache-vampire.outputs.cache-hit != 'true' }}
        run: ./vampire-install.sh

      - if: ${{ steps.cache-vampire.outputs.cache-hit == 'true' }}
        run: cp repositories/vampire/build/vampire reason/assets/bin

      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv sync
      - run: |
          uv run task test