name: Reason check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: sudo apt install -y build-essential cmake clang zlib1g-dev libgmp-dev python3 curl
#      - run: |
#          ./vampire-install.sh
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh .
      - run: uv sync
#      - run: |
#          uv run task test